# Generated by Django 5.1.5 on 2025-01-22 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('location', models.TextField()),
                ('complaint_type', models.CharField(choices=[('Roads', 'Roads'), ('Transportation', 'Transportation'), ('Sewage & Drainage', 'Sewage & Drainage'), ('Electricity & Street Lights', 'Electricity & Street Lights'), ('Solid Waste Management', 'Solid Waste Management'), ('Health & Sanitation', 'Health & Sanitation'), ('Parks & Public Places', 'Parks & Public Places'), ('Environment Concerns', 'Environment Concerns'), ('Others', 'Others (Legal & Complaints Cell)')], max_length=50)),
                ('details', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='complaint_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
